In [1]:
# test if the fitting of 4 points gives zero error

import sys
import os
sys.path.append('..')

In [2]:
from skimage.transform._geometric import ProjectiveTransform, AffineTransform as AFT
from multiviewmoseg.transform.affine import AffineTransform
from multiviewmoseg.transform.utils import homo2nonhomo, nonhomo2homo

In [3]:
import numpy as np

src_gt = np.random.randn(4, 2)
dst_gt = np.random.randn(4, 2)

In [4]:
gt_affine = AFT()
gt_affine.estimate(src=src_gt, dst=dst_gt)
A = gt_affine.params

In [5]:
src = np.random.randn(30, 2)
dst = homo2nonhomo(nonhomo2homo(src) @ A.T)
dst_noise = dst + 0.01 * np.random.randn(30, 2)

In [6]:
test_transform = AffineTransform()
test_transform.fit(src=src, dst=dst)

In [7]:
A, test_transform.params, test_transform.residuals(src, dst)

(array([[ 2.20053009, -0.39445448, -1.24217901],
        [ 1.16619057,  0.89861607, -0.36249126],
        [ 0.        ,  0.        ,  1.        ]]),
 array([[ 2.20053009, -0.39445448, -1.24217901],
        [ 1.16619057,  0.89861607, -0.36249126],
        [ 0.        ,  0.        ,  1.        ]]),
 array([1.85972610e-30, 2.46519033e-31, 4.94270661e-30, 2.85037632e-30,
        7.70371978e-32, 1.54074396e-30, 2.52759046e-30, 5.17689969e-31,
        2.72711680e-31, 1.47911420e-31, 1.63010710e-30, 6.16297582e-31,
        7.06277029e-30, 1.10009118e-30, 2.41896801e-30, 2.28030105e-30,
        1.55584325e-29, 1.30192864e-31, 1.14015053e-31, 1.56416326e-29,
        2.11513330e-29, 2.28030105e-30, 1.23259516e-32, 2.46519033e-32,
        9.67298315e-30, 4.69156534e-31, 3.05683601e-30, 1.23567665e-30,
        2.77333912e-31, 2.45594587e-30]))

In [11]:
test_transform.fit(src=src, dst=dst_noise)
A, test_transform.params, test_transform.residuals(src, dst_noise)

(array([[ 2.20053009, -0.39445448, -1.24217901],
        [ 1.16619057,  0.89861607, -0.36249126],
        [ 0.        ,  0.        ,  1.        ]]),
 array([[ 2.19953483, -0.39506606, -1.24257696],
        [ 1.16660157,  0.89984006, -0.36086573],
        [ 0.        ,  0.        ,  1.        ]]),
 array([3.46314562e-04, 3.28335422e-04, 3.90242239e-05, 3.62612644e-04,
        1.31239000e-04, 4.78444858e-04, 1.02914161e-05, 3.54634727e-04,
        2.94833215e-04, 1.41801949e-04, 4.30683167e-04, 4.25101340e-05,
        1.70213132e-04, 4.09593017e-04, 5.03514852e-04, 8.61274204e-05,
        2.03930529e-04, 6.95595583e-04, 1.31478176e-04, 8.50637980e-04,
        3.12017703e-04, 4.06663181e-04, 1.07241749e-03, 2.63872856e-04,
        1.28646346e-04, 2.28120914e-05, 7.89095137e-04, 1.70486234e-04,
        1.28569286e-04, 2.49213857e-04]))