In [1]:
# test if the fitting of 4 points gives zero error

import sys
import os
sys.path.append('..')

In [2]:
from skimage.transform._geometric import ProjectiveTransform, AffineTransform as AFT
from multiviewmoseg.transform.affine import AffineTransform
from multiviewmoseg.transform.utils import homo2inhomo, inhomo2homo
from multiviewmoseg.transform.homography import HomographyTransform

In [3]:
import numpy as np

src_gt = np.random.randn(4, 2)
dst_gt = np.random.randn(4, 2)

In [4]:
gt_homo = ProjectiveTransform()
gt_homo.estimate(src=src_gt, dst=dst_gt)
A = gt_homo.params
A

array([[ 1.73959091,  0.01336546, -0.83379056],
       [-1.28551742, -0.03138279,  0.56708909],
       [-2.22684227,  0.1264937 ,  1.        ]])

In [5]:
src = np.random.randn(30, 2)
dst = homo2inhomo(inhomo2homo(src) @ A.T)
dst_noise = dst + 0.01 * np.random.randn(30, 2)

In [6]:
test_transform = HomographyTransform()

In [8]:
%%timeit
test_transform.fit(src=src, dst=dst)

91.5 µs ± 481 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [10]:
test_transform.fit(src=src, dst=dst)
A, test_transform.params, test_transform.params - A, test_transform.residuals(src, dst)

(array([[ 1.86689637, -1.40363705, -2.09298592],
        [ 0.73338288,  2.73952573,  0.31662066],
        [-1.05015123,  3.29410305,  1.        ]]),
 array([[ 1.86689637, -1.40363705, -2.09298592],
        [ 0.73338288,  2.73952573,  0.31662066],
        [-1.05015123,  3.29410305,  1.        ]]),
 array([[ 2.44249065e-15, -4.44089210e-16, -3.10862447e-15],
        [ 4.44089210e-16,  2.22044605e-15,  7.21644966e-16],
        [-2.22044605e-15,  3.55271368e-15,  0.00000000e+00]]),
 array([9.36772325e-31, 1.67787017e-29, 6.53275437e-31, 8.03960196e-30,
        1.34915244e-29, 6.68374728e-30, 1.21971626e-30, 4.65920972e-30,
        7.71759418e-28, 6.82921975e-27, 1.04601107e-29, 5.49549665e-30,
        6.42921638e-29, 1.29422492e-30, 1.34352873e-30, 2.35444936e-30,
        1.70221392e-29, 3.65541503e-30, 3.35208107e-30, 1.01274025e-27,
        9.65368533e-29, 3.16468808e-30, 4.06756404e-31, 5.37719640e-30,
        1.21102475e-30, 6.93334780e-31, 2.21497351e-29, 1.81838602e-29,
        4.837

In [9]:
test_transform.fit(src=src, dst=dst_noise)
A, test_transform.params, test_transform.residuals(src, dst_noise)

(array([[ 1.86689637, -1.40363705, -2.09298592],
        [ 0.73338288,  2.73952573,  0.31662066],
        [-1.05015123,  3.29410305,  1.        ]]),
 array([[ 1.86183955, -1.40833861, -2.0940062 ],
        [ 0.73670092,  2.72686672,  0.31286666],
        [-1.04984218,  3.2910912 ,  1.        ]]),
 array([5.93769590e-04, 5.14722094e-03, 5.58981404e-03, 8.54399037e-05,
        3.33653607e-04, 1.95303855e-03, 1.66673776e-03, 8.51017042e-04,
        6.02240717e-04, 5.89582188e-04, 1.95009905e-03, 8.58856078e-03,
        2.64970900e-03, 6.87529129e-04, 2.69291856e-03, 2.19145370e-03,
        2.43342302e-04, 9.58149279e-03, 6.59306133e-04, 2.75216174e-04,
        8.05663371e-03, 3.47974964e-04, 5.66308044e-03, 9.55050346e-06,
        2.29878266e-03, 1.90365484e-02, 1.10409735e-03, 3.31983468e-03,
        7.40217846e-03, 4.96073009e-02]))